server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    port: 6379
    host: 192.168.190.15

mybatis:
  type-aliases-package: com.baizhi.cxx.entity
  mapper-locations: classpath:com/baizhi/cxx/mapper/*Mapper.xml

logging:
  level:
    root: error
    com.baizhi.cxx.dao: debug
    com.baizhi.cxx.service: debug
    com.baizhi.cxx.serviceimpl: debug
    com.baizhi.cxx.controller: debug


